// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6Pgqnf2ExiYckbu-Q6rrsoi5p_RMEPY',
    appId: '1:273513496972:web:ead4e4c829f95c87ee16a9',
    messagingSenderId: '273513496972',
    projectId: 'mealmastermind-52f45',
    authDomain: 'mealmastermind-52f45.firebaseapp.com',
    storageBucket: 'mealmastermind-52f45.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcuJi7v4mTZIMspEFD2O_5IKXhunn0CpM',
    appId: '1:273513496972:android:814bcd70e0ac4f0aee16a9',
    messagingSenderId: '273513496972',
    projectId: 'mealmastermind-52f45',
    storageBucket: 'mealmastermind-52f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm30fXxWhQG5W6pIWU91hNTudRNC3cL4Y',
    appId: '1:273513496972:ios:edafd4959e35b2fcee16a9',
    messagingSenderId: '273513496972',
    projectId: 'mealmastermind-52f45',
    storageBucket: 'mealmastermind-52f45.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
